[package]
name = "fast-rng"
version = "0.1.0"
authors = ["Elichai Turkel <elichai.turkel@gmail.com>"]

[dependencies]
random-trait = { path = "../random-trait" }

doc-comment = { version = "0.3", optional = true }


[features]
default = ["std"]
std = []