os: Visual Studio 2017

environment:
  matrix:

    ### MSVC Toolchains ###

    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc

    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc

    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc

    - channel: 1.13.0
      target: x86_64-pc-windows-msvc
    - channel: 1.13.0
      target: i686-pc-windows-msvc

    - channel: 1.19.0
      target: x86_64-pc-windows-msvc
    - channel: 1.19.0
      target: i686-pc-windows-msvc

    - channel: 1.20.0
      target: x86_64-pc-windows-msvc
    - channel: 1.20.0
      target: i686-pc-windows-msvc

    - channel: 1.21.0
      target: x86_64-pc-windows-msvc
    - channel: 1.21.0
      target: i686-pc-windows-msvc

    - channel: 1.22.0
      target: x86_64-pc-windows-msvc
    - channel: 1.22.0
      target: i686-pc-windows-msvc

    - channel: 1.25.0
      target: x86_64-pc-windows-msvc
    - channel: 1.25.0
      target: i686-pc-windows-msvc

    - channel: 1.26.0
      target: x86_64-pc-windows-msvc
    - channel: 1.26.0
      target: i686-pc-windows-msvc

    - channel: 1.27.0
      target: x86_64-pc-windows-msvc
    - channel: 1.27.0
      target: i686-pc-windows-msvc

    - channel: 1.28.0
      target: x86_64-pc-windows-msvc
    - channel: 1.28.0
      target: i686-pc-windows-msvc

    - channel: 1.31.0
      target: x86_64-pc-windows-msvc
    - channel: 1.31.0
      target: i686-pc-windows-msvc
    - channel: 1.31.0

      target: x86_64-pc-windows-msvc
    - channel: 1.34.0
      target: i686-pc-windows-msvc
    - channel: 1.34.0

      target: x86_64-pc-windows-msvc
    - channel: 1.36.0
      target: i686-pc-windows-msvc
    - channel: 1.36.0
    ### GNU Toolchains ###

    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu

    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu

    - channel: nightly
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu

    - channel: 1.13.0
      target: x86_64-pc-windows-gnu
    - channel: 1.13.0
      target: i686-pc-windows-gnu

    - channel: 1.19.0
      target: x86_64-pc-windows-gnu
    - channel: 1.19.0
      target: i686-pc-windows-gnu

    - channel: 1.20.0
      target: x86_64-pc-windows-gnu
    - channel: 1.20.0
      target: i686-pc-windows-gnu

    - channel: 1.21.0
      target: x86_64-pc-windows-gnu
    - channel: 1.21.0
      target: i686-pc-windows-gnu

    - channel: 1.22.0
      target: x86_64-pc-windows-gnu
    - channel: 1.22.0
      target: i686-pc-windows-gnu

    - channel: 1.25.0
      target: x86_64-pc-windows-gnu
    - channel: 1.25.0
      target: i686-pc-windows-gnu

    - channel: 1.26.0
      target: x86_64-pc-windows-gnu
    - channel: 1.26.0
      target: i686-pc-windows-gnu

    - channel: 1.27.0
      target: x86_64-pc-windows-gnu
    - channel: 1.27.0
      target: i686-pc-windows-gnu

    - channel: 1.28.0
      target: x86_64-pc-windows-gnu
    - channel: 1.28.0
      target: i686-pc-windows-gnu

    - channel: 1.31.0
      target: x86_64-pc-windows-gnu
    - channel: 1.31.0
      target: i686-pc-windows-gnu
    - channel: 1.31.0

      target: x86_64-pc-windows-gnu
    - channel: 1.34.0
      target: i686-pc-windows-gnu
    - channel: 1.34.0

      target: x86_64-pc-windows-gnu
    - channel: 1.36.0
      target: i686-pc-windows-gnu
    - channel: 1.36.0

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

before_test:
  - if "%channel%"=="stable" (
    cd "%APPVEYOR_BUILD_FOLDER%/random-trait" &&
    rustup component add clippy-preview rustfmt &&
    cargo fmt --all -- --check &&
    cargo clippy --all-targets --all-features -- -Dwarnings -Aclippy::transmute_int_to_float -Aclippy::new-without-default &&
    cd "%APPVEYOR_BUILD_FOLDER%/random-fast-rng" &&
    rustup component add clippy-preview rustfmt &&
    cargo fmt --all -- --check &&
    cargo clippy --all-targets --all-features -- -Dwarnings -Aclippy::transmute_int_to_float -Aclippy::new-without-default)

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%/random-trait"
  - cargo build --verbose
  - cargo test --verbose
  - if "%channel%"=="stable" (cargo test --features=doc-comment)
  - cd "%APPVEYOR_BUILD_FOLDER%/random-fast-rng"
  - cargo build --verbose
  - cargo test --verbose
  - if "%channel%"=="stable" (cargo test --features=doc-comment)

cache:
  - 'C:\Users\appveyor\.cargo'
  - 'C:\Users\appveyor\.rustup'
  - 'target'
