language: rust
sudo: false
cache: false
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - beta
  - nightly
  - 1.13.0
  - 1.19.0
  - 1.20.0
  - 1.21.0
  - 1.22.0
  - 1.25.0
  - 1.26.0
  - 1.27.0
  - 1.28.0
  - 1.31.0
  - 1.34.0
  - 1.36.0

script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then cargo test --features=doc-comment; fi

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
      rustup component add clippy-preview rustfmt;
      cargo fmt --all -- --check;
      cargo clippy --all-targets --all-features -- -Dwarnings -Aclippy::transmute_int_to_float -Aclippy::new-without-default;
    fi
#  - if [ ${TRAVIS_RUST_VERSION} == "nightly" ]; then
#      rustup component add miri;
#      cargo miri setup;
#      cargo miri test -- -- -Zunstable-options --exclude-should-panic;
#    fi

notifications:
  email:
    on_success: never
