[package]
name = "random-trait"
version = "0.1.0"
authors = ["Elichai Turkel <elichai.turkel@gmail.com>"]

[dependencies]
doc-comment = { version = "0.3", optional = true }

[features]
u128 = []

[dev-dependencies]
doc-comment = "0.3"

